[project]
name = "aliciadata-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.75.0",
    "chevron>=0.14.0",
    "dotenv>=0.9.9",
    "gradio>=6.3.0",
    "openai>=2.15.0",
    "psycopg2-binary>=2.9.11",
    "requests>=2.32.5",
]
